name: Release to NPM

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install Dependencies (NPM CI)
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Set Package Version from Git Tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Release Version: $VERSION"

          # Aktualisiert die package.json auf die Tag-Version
          npm version $VERSION --no-git-tag-version

      - name: Authenticate and Publish to NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
